version: '3'

services:
  gateway:
    container_name: gateway
    env_file: ./.env
    environment:
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_DEFAULT_SERVICE: ${GATEWAY_DEFAULT_SERVICE}
      GATEWAY_API_SERVICE: ${GATEWAY_API_SERVICE}
    build:
      context: ./compose/gateway
    ports:
      - 80:80
      - 443:443
  plantcare:
    container_name: plantcare
    env_file: ./.env
    image: lmbautista/plantcare:latest
    environment:
      RAILS_ENV: production
    depends_on:
      - gateway
      - wtever-api
      - db
    expose:
      - 8080
  wtever-api: &wtever-api
    container_name: wtever-api
    env_file: ./.env
    image: lmbautista/wtever-api:latest
    environment:
      RAILS_ENV: production
      REDIS_WTEVER_API_URL: redis://wtever-api-redis:6379
    depends_on:
      - gateway
      - db
      - wtever-api-redis
  db:
    container_name: db
    env_file: ./.env
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
  wtever-api-redis:
    image: redis
    container_name: wtever-api-redis
    volumes:
      - ./compose/wtever-api-redis:/data
  wtever-api-sidekiq:
    <<: *wtever-api
    container_name: wtever-api-sidekiq
    command: bundle exec sidekiq -C ./config/sidekiq.yml